{% set name = "sqlitedict" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2affcc301aacd4da7511692601ecbde392294205af418498f7d6d3ec0dbcad56

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - sqlitedict

about:
  home: https://github.com/RaRe-Technologies/sqlitedict
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE.md
  summary: Persistent dict in Python, backed up by sqlite3 and pickle, multithread-safe.
  doc_url: https://github.com/RaRe-Technologies/sqlitedict
  dev_url: https://github.com/RaRe-Technologies/sqlitedict

extra:
  recipe-maintainers:
    - notestaff
    - synapticarbors
